import type { PokemonCatalog } from "@/domain/pokemon/catalog";

export const inventoryTestCatalog: PokemonCatalog = {
  dataVersion: "test-data-v1",
  entries: [
    {
      speciesId: "azumarill",
      speciesName: "Azumarill",
      dex: 184,
      types: ["water", "fairy"],
      tags: [],
      isReleased: true,
      isShadow: false,
      isShadowEligible: false,
      baseStats: {
        attack: 112,
        defense: 152,
        hp: 225,
      },
      levelFloor: 1,
      levelCap: 50,
      evolutionIds: [],
      fastMoves: [
        {
          id: "BUBBLE",
          name: "Bubble",
          type: "water",
          kind: "fast",
          power: 8,
          energy: 0,
          energyGain: 11,
          turns: 3,
          isLegacy: false,
          isElite: false,
        },
      ],
      chargedMoves: [
        {
          id: "ICE_BEAM",
          name: "Ice Beam",
          type: "ice",
          kind: "charged",
          power: 90,
          energy: 55,
          energyGain: 0,
          turns: 1,
          isLegacy: false,
          isElite: false,
        },
        {
          id: "PLAY_ROUGH",
          name: "Play Rough",
          type: "fairy",
          kind: "charged",
          power: 90,
          energy: 60,
          energyGain: 0,
          turns: 1,
          isLegacy: false,
          isElite: false,
        },
      ],
      defaultGreatLeagueIvs: {
        level: 45.5,
        attack: 0,
        defense: 15,
        hp: 15,
      },
      ranking: {
        rank: 5,
        score: 94.2,
        rating: 612,
        recommendedMoveIds: ["BUBBLE", "ICE_BEAM", "PLAY_ROUGH"],
        matchups: [
          { speciesId: "altaria", rating: 646 },
          { speciesId: "whiscash", rating: 552 },
        ],
        counters: [
          { speciesId: "whiscash", rating: 314 },
          { speciesId: "altaria", rating: 400 },
        ],
        roleScores: {
          lead: 84.5,
          closer: 87.3,
          switch: 69.9,
          charger: 85.7,
          attacker: 92,
          consistency: 93.1,
        },
      },
      isMeta: true,
    },
    {
      speciesId: "whiscash",
      speciesName: "Whiscash",
      dex: 340,
      types: ["water", "ground"],
      tags: [],
      isReleased: true,
      isShadow: false,
      isShadowEligible: true,
      baseStats: { attack: 151, defense: 141, hp: 242 },
      levelFloor: 1,
      levelCap: 50,
      evolutionIds: [],
      fastMoves: [
        {
          id: "MUD_SHOT",
          name: "Mud Shot",
          type: "ground",
          kind: "fast",
          power: 3,
          energy: 0,
          energyGain: 9,
          turns: 2,
          isLegacy: false,
          isElite: false,
        },
      ],
      chargedMoves: [
        {
          id: "SCALD",
          name: "Scald",
          type: "water",
          kind: "charged",
          power: 85,
          energy: 50,
          energyGain: 0,
          turns: 1,
          isLegacy: false,
          isElite: false,
        },
        {
          id: "BLIZZARD",
          name: "Blizzard",
          type: "ice",
          kind: "charged",
          power: 140,
          energy: 75,
          energyGain: 0,
          turns: 1,
          isLegacy: false,
          isElite: false,
        },
      ],
      defaultGreatLeagueIvs: {
        level: 27,
        attack: 4,
        defense: 15,
        hp: 15,
      },
      isMeta: false,
    },
    {
      speciesId: "altaria",
      speciesName: "Altaria",
      dex: 334,
      types: ["dragon", "flying"],
      tags: [],
      isReleased: true,
      isShadow: false,
      isShadowEligible: true,
      baseStats: { attack: 141, defense: 201, hp: 181 },
      levelFloor: 1,
      levelCap: 50,
      evolutionIds: [],
      fastMoves: [
        {
          id: "DRAGON_BREATH",
          name: "Dragon Breath",
          type: "dragon",
          kind: "fast",
          power: 3,
          energy: 0,
          energyGain: 4,
          turns: 1,
          isLegacy: false,
          isElite: false,
        },
      ],
      chargedMoves: [
        {
          id: "SKY_ATTACK",
          name: "Sky Attack",
          type: "flying",
          kind: "charged",
          power: 75,
          energy: 50,
          energyGain: 0,
          turns: 1,
          isLegacy: false,
          isElite: false,
        },
        {
          id: "MOONBLAST",
          name: "Moonblast",
          type: "fairy",
          kind: "charged",
          power: 110,
          energy: 60,
          energyGain: 0,
          turns: 1,
          isLegacy: false,
          isElite: false,
        },
      ],
      defaultGreatLeagueIvs: {
        level: 29,
        attack: 0,
        defense: 14,
        hp: 15,
      },
      ranking: {
        rank: 30,
        score: 80,
        rating: 520,
        recommendedMoveIds: [
          "DRAGON_BREATH",
          "SKY_ATTACK",
          "MOONBLAST",
        ],
        matchups: [{ speciesId: "whiscash", rating: 610 }],
        counters: [
          { speciesId: "azumarill", rating: 300 },
          { speciesId: "whiscash", rating: 420 },
        ],
        roleScores: {
          lead: 70,
          closer: 72,
          switch: 65,
          charger: 68,
          attacker: 75,
          consistency: 78,
        },
      },
      isMeta: true,
    },
  ],
  diagnostics: {
    duplicatePokemonIds: [],
    duplicateMoveIds: [],
    duplicateRankingIds: [],
    danglingPokemonMoveIds: [],
    rankingSpeciesNotInGameMaster: [],
    rankingMoveIdsNotInGameMaster: [],
    metaSpeciesNotInGameMaster: [],
    metaMoveIdsNotInGameMaster: [],
  },
};
